# A basic neural network implementation

In [1]:
import numpy as np

np.random.seed(0)

# X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

# scale units
X = X / np.amax(X, axis=0) # maximum of X array
y = y / 100 # max test score is 100

In [2]:
X

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.66666667]])

In [3]:
y

array([[0.92],
       [0.86],
       [0.89]])

In [4]:
class NeuralNetwork(object):

    def __init__(self):
        self.input_dim = 2
        self.output_dim = 1
        self.hidden_dim = 3
    
        self.W1 = np.random.randn(self.input_dim, self.hidden_dim)
        self.W2 = np.random.randn(self.hidden_dim, self.output_dim)

    def forward(self, X):
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
        return self.sigmoid(self.z3) # final activation function
    
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))


In [5]:
nn = NeuralNetwork()

In [6]:
nn.forward(X)

array([[0.67727117],
       [0.65870127],
       [0.67437581]])

In [7]:
print('predicted', nn.forward(X))
print('actual', y)

predicted [[0.67727117]
 [0.65870127]
 [0.67437581]]
actual [[0.92]
 [0.86]
 [0.89]]
